# Generated by Django 4.0.2 on 2022-03-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_book_biography_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biography',
            old_name='test',
            new_name='text',
        ),
    ]
